# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

pages: # the job must be named pages
  # image: node:latest
  # cache:
  #   paths:
  #     - node_modules/
  stage: deploy
  # script:
    # - npm ci
    # - npm run verprod
    # - mv public public-vue # GitLab Pages hooks on the public folder
    # - mv dist/spa public # rename the dist folder (result of npm run build)
  script:
    - mv public publicX
    - mkdir .public
    - cp -R dist/* .public
    - mv .public public
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  # only:
  #   - tjey
